#!/usr/bin/perl
# addpriority - adds a priority setting to  lists that do not already have one
# (and then they get adjusted by the adjustpriority script). This is needed
# because sympa's --set_list_priority option doesn't currently work if the
# list does not have a priority

$priority='8';
$sympa='/home/sympa/bin/sympa.pl';
$expl='/home/sympa/expl';
$file=$ARGV[0];

open(LISTS, "$file") or die "cannot open $file\n";

while (<LISTS>) {
  chomp;
  $list=$_;

  if ( ! `grep -H priority $expl/$list/config` ) {
    print "$list: no priority detected setting to $priority\n";
    `echo "priority $priority" >>$expl/$list/config`;
  }
  
}
# do one reload of the configs at the end
`$sympa --reload_list_config`;
