#!/usr/bin/perl
# counts - list, subscription, user counts
# NOTE: this script requires the current user has read access to the db

$lists=`mysql --batch --database=sympa --skip-column-names --execute "select count(name_list) from list_table where status_list = 'open'"';
$sub=`mysql --batch --database=sympa --skip-column-names --execute "select count(user_subscriber) from subscriber_table"`;
$users=`mysql --batch --database=sympa --skip-column-names --execute "select count(email_user) from user_table"`;

if ( $ARGV[0] eq '-h' ) {
   print "As of ".`date`."<br>\n";
   print "Lists: <b>$lists</b>  ";
   print "Total Subscriptions: <b>$sub</b>  ";
   print "Unique Users: <b>$users</b>\n";
} else {
   print "As of ".`date`."\n";
   print "Lists: $lists\n";
   print "Total Subscriptions: $sub\n";
   print "Unique Users: $users\n";
}
