#!/usr/bin/perl -w
# topdomains - list the top 25 domains by user count,
#  also lists the total users and unique domains
# NOTE: this script doesn't check the validity of addresses or domains
#  so the count might include them if those haven't been cleaned up
# NOTE: this script requires the current user has read access to the db

use vars qw($rundump %domains %count $key $percent);

$rundump='mysql --batch --database=sympa --skip-column-names --execute \
  "select email_user from user_table"';

open(LIST,"$rundump|") or die "Cannot get addresses from sympa db\n";

while (<LIST>) {
   # because we have bogus addresses, this regex doesn't always match, so if it
   if ( m/@(.*)>?$/ ) {
      $domains{$1}++;
      $count++;
   };
}

$dcount = scalar keys %domains;
print "Total users: ".$count." Total domains: ". $dcount ."\n";

print "Domain:                                                    users (\% of total)\n";

format Output =
@<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<... @>>>>>>> (@#.##%)
$key,                                                   $domains{$key}, $percent
.
$~='Output';

foreach $key ((sort { $domains{$b} <=> $domains{$a} } keys %domains)[0..24]) {
   $percent=$domains{$key}/$count*100;
   write;
}
