#!/usr/bin/perl
# toplists - top $num lists and their subscriber count, sorted
#  descending by count
# NOTE: this script requires the current user has read access to the db

$num=25;
$date=`date`;
chomp($date);

$sql=qq(mysql --batch --database=sympa --skip-column-names --execute "SELECT subscriber_table.list_subscriber AS listname, count(subscriber_table.list_subscriber) AS subscribers FROM subscriber_table, list_table where subscriber_table.list_subscriber=list_table.name_list and list_table.status_list='open' GROUP BY subscriber_table.list_subscriber ORDER BY subscribers DESC LIMIT $num;");

open(COUNTS, "$sql|") or die "cannot get subscriber counts from database\n";

format Wiki =
|[@*->https://lists.riseup.net/www/info/@*]|@*|
  $list,                            $list,$counts{$list}
.

format Plain =
@* @*
$list, $counts{$list}
.

format Html =
<tr><td><a href="https://lists.riseup.net/www/info/@*">@*</a></td><td align=right>@*</td></tr>
                                                $list, $list,     $counts{$list}
.

format Pcre =
/@(bounce\+.*==)?@*(-owner)?@lists\.riseup\.net$/ [10.0.1.44]
"^", $list, "@"
.

if ( $ARGV[0] eq '-w' ) {
   $~='Wiki';
   print "h3. Top $num lists by size\n\n";
   print "(generated ".$date.")\n\n";
   print "|_.List name|_.Subscribers|\n";
} elsif ($ARGV[0] eq '-h' ) {
   $~='Html';
   print "<style>table.single{border: 1px solid;border-collapse: collapse;}\n.single td, .single th{border-width: 1px 1px 1px 1px;border-style: solid;}\n</style>\n";
   print "<h3>Top $num lists by size</h3>\n";
   print "(<i>generated ".$date."</i>)\n";
   print "<table class=\"single\">\n";
   print "<tr><th align=center>List name</th><th align=center>Subscribers</th></tr>\n";
} elsif ($ARGV[0] eq '-r' ) {
   $~='Pcre';
} else {
   $~='Plain';
   print "Top $num lists by size\n";
   print "(generated ".$date.")\n";
}


while (<COUNTS>) {
   ($list, $count) = split /\t/;
   $counts{$list}=$count;
   write;
}

if ($ARGV[0] eq '-h' ) {
   print "</table>\n";
}
