#!/bin/sh
 
#
# prints a listing of all the lists with bounces and the number of
# bouncing email accounts for the list, ordered by bounce count.
#

source ./common

mysql  -u $DB_USER -p$DB_PASS --batch --database=$DB_NAME --execute \
"SELECT count(*) as 'bounce_count', list_subscriber as 'list'  \
FROM subscriber_table WHERE bounce_subscriber \
<> 'NULL' GROUP BY list_subscriber ORDER BY bounce_count"
