#!/bin/sh
# countbouncesuser - prints a listing of all the users with a bounce
#  score over 75 and prints bounce score, list, user; ordered by bounce score.
# NOTE: this script requires the current user has read access to the db

mysql --batch --database=sympa --execute \
"SELECT bounce_score_subscriber,list_subscriber,user_subscriber FROM \
subscriber_table WHERE bounce_score_subscriber > 75 ORDER BY \
bounce_score_subscriber"
