#!/bin/sh

source ./common

mysql  -u $DB_USER -p$DB_PASS --batch --database=$DB_NAME --execute \
"select email_user, password_user from user_table where email_user like '%$1%'" > /tmp/out1

echo ""

mysql -u $DB_USER -p$DB_PASS --batch --database=$DB_NAME --execute \
"select list_subscriber, user_subscriber from subscriber_table where user_subscriber like '%$1%'" > /tmp/out2

cat /tmp/out1 | awk '{print $1}' | sort | uniq > /tmp/out1_sort
cat /tmp/out2 | awk '{print $2}' | sort | uniq > /tmp/out2_sort
cat /tmp/out1_sort >> /tmp/out2_sort
cat /tmp/out2_sort | sort | uniq > /root/final

