#!/bin/sh
# finduser - list users in the subscriber table that match a substring
# NOTE: this script requires the current user has read access to the db

mysql --batch --database=sympa --execute \
"select user_subscriber from subscriber_table where user_subscriber like '%$1%'"

