#!/bin/sh
# listbounces - prints a listing of all the lists with people with a bounce
#  score over 75 and the number of people over 75 for the list,
#  ordered by bounce count.
# NOTE: this script requires the current user has read access to the db

mysql --batch --database=sympa --execute \
"SELECT count(*) as 'bounce_count', list_subscriber as 'list'  \
FROM subscriber_table WHERE bounce_subscriber <> 'NULL' AND \
bounce_score_subscriber > 75 GROUP BY list_subscriber ORDER BY bounce_count"
