#!/bin/sh

#
# forces an immediate remind task for a particular list. 
# must be run as user sympa
#
# usage: 
# remindnow <listname>
#

cp ~/etc/list_task_models.disabled/remind.now.task ~/spool/task/`date +%s`.INIT.remind.$1
